### PR TITLE
feat: Add Swipe Support

### PR DESCRIPTION
**Pull request by pixel-shock**
Hi there,

first of all: **THIS APP IS ONE OF THE BEST APPS I'VE SEEN SO FAR!!! THANK YOU VERY MUCH**

I've added Swipe Gesture Support and this was my first AndroidApp / Kotlin stuff I've done so far, so please be nice to me when reviewing this PR :wink:

@sds100 I was not sure why I can't assign a reviewer. Maybe just a missing permission for me. So if you have time please assign it to someone or to you 😉

### CODE REVIEW

**Comment by sds100** [comment]
Wow, a lot of people have been asking for this. Thank you so much! I'm happy to hear you really like the app. I'll review it and test it soon.

**Comment by pixel-shock** [comment]
No Seth, THANK YOU for this masterpiece of an app. Glad if I can help IF the PR will be accepted. 😉
I tried to adapt everthing you did in terms of date schema and views.

**Comment by sds100** [comment]
The code looked perfect! just adjusted a couple tiny things. The UI could be a bit more intuitive, i can foresee people being a bit confused. I don't really have time to work on this anymore.

**Comment by pixel-shock** [comment]
Awesome. Thank you. Maybe I can change the screenshot selector to fetch both touch events. Like for start and end so the user don't have to select 2 screenshots. I will create an improvement ticket for my self 😉

**Comment by sds100** [comment]
Yeah, that would be great!

**Comment by pixel-shock** [comment]
Hi @sds100 ,

fyi: I am currently testing the new view/ layout for the screenshot selection. I changed the selection to a radio button, because

1. I've tested it with "1st touch = start coords, 2nd touch = end coords", but this wasn't good to handle for the user, because if a touch wasn't precise on the position on which the user wanted to touch, then the user would have to redo the end coords as well - you know what I mean?
2. next thing what I am currently implementing is multitouch, most of the custom launchers have gesture recognition for 2 finger swipe and 3 finger swipe so I think this will be a good addition
3. the multitouch for pinch gesture will be the next thing to implement I think

image

**Comment by sds100** [comment]
Sounds good! I understand why you need the radio buttons so that's fine with me.

**Pull request merged**
