### PR TITLE
GL513 profile pic swap

### PR DESCRIPTION
**Pull request by GL513**
Going from 427x427 to 4kx4k

### CODE REVIEW

**Comment by GL513** [comment]
@sds100 cant request you to review for some reason, so here we are.

**Comment by sds100** [comment]
can you assign me as a reviewer now? and can you delete issues now?

**Comment by GL513** [comment]
> can you assign me as a reviewer now? and can you delete issues now?

Yep, all good

**Comment by sds100** [comment]
cool, i've given you write permissions to the repository - be careful! 😂 NEVER **force push**

**Comment by GL513** [comment]
> cool, i've given you write permissions to the repository - be careful! 😂 NEVER **force push**

Got it 👍
I wont directly commit or merge PRs myself anyway

**Pull request merged**
