### PR TITLE
Feature/550 swipegesture

### PR DESCRIPTION
**Pull request by jimmyli97**

### CODE REVIEW

**Comment by sds100** [comment]
Thank you! I'll check this out at some point, hopefully today. It's great that all your code seems to follow the Key Mapper style/architecture. Was it complicated to figure out? Any improvements that you would suggest?

**Comment by jimmyli97** [comment]
No problem! This was my attempt at learning Android programming so the main
hurdle was learning how android works. The framework works for what I was
trying to do, which is excellent. I learned it mostly through searching for
how you implemented screen tapping and copying and modifying it. If I had
to nitpick I would prefer to have one consistent searchable identifier for
ActionData, ActionId, ActionEntity, Navigation rather than for instance
"id_pick_tap_coordinate" vs "tapcoordinateaction", etc. Makes it harder to
search since searching for "tap" returns too many irrelevant results.

Some additional issues I noticed while testing today:
* occasional crash while loading screenshot
* unable to recover accessibility service after crash by restarting it,
keeps saying checking if accessibility service is crashed and then it says
it is crashed

Unfortunately I won't have time to debug this for a month or so, but I
figured I would make the pull request so other people can see it and modify
it if they want.

**Comment by sds100** [comment]
Thank you for the feedback.
1. They all have to be separate but I'll move all actions to be subclasses of ActionData so you can type `ActionData.` and then get a list of all the actions. The ActionEntity is the model for how the actions are stored in the database. It isn't a great way of doing it since I made that design decision 2 years ago when I was still learning the best way to do things. 😄
2. Key Mapper should have captured that crash stacktrace in it's log. Can you send me the log. You can find it at the bottom of the Key Mapper settings.
3. Yeah, I've also had the same issue but I'm not quite sure why it is happening. It happens randomly for me.

**Comment by jimmyli97** [comment]
1. That's a good idea, thank you. Totally understand, even doing this small
project I had to keep starting from scratch as to how I designed it.
2. Screenshot crash is attached.
3. The accessibility service crash is consistent for me (right now the
debug version is unusable, haven't tried reinstalling it yet). Log
attached. Also attached a third report, not sure what I was doing before it
but it was either a screenshot or an accessibility crash.

**Pull request closed without merging**
