### PR TITLE
Feature: Interaction with screen element

### PR DESCRIPTION
**Pull request by pixel-shock**
Hi @sds100 🙋‍♂️,

I added a new action for interacting with screen elements by ID. 
The user has the possibility to select the ui elements via the simple list recycler view and can choose what action should be performed. Also if the action should be only performed if the element is visible or not.

### CODE REVIEW

**Comment by sds100** [comment]
Can you fix the merge conflicts by merging `develop` into this branch. Then I'll review your code :)

**Comment by sds100** [comment]
I see that you're also doing german translations 😄

**Comment by pixel-shock** [comment]
I will do it after my vacation. And I created a new branch with both of my PRs to resolve issues and some ui fixes. 
So maybe it will be better if we check this after my vacation

**Comment by sds100** [comment]
Sounds good :)

**Comment by pixel-shock** [comment]
I close this one, because the follow up with the latest code is here: https://github.com/keymapperorg/KeyMapper/pull/1182

**Pull request closed without merging**
