### PR TITLE
feat: Add Swipe Support - Add multi-touch Swipe support

### PR DESCRIPTION
**Pull request by pixel-shock**
Hi @sds100 ,

* as said, I've added multi-touch swipe support for the "swipe" action.
* I've also added the radio buttons for the user to choose between start and end coordiates and removed the double "select screenshot" button
* I've added some documentation to the function with triggers the multitouch.
* At the screenshot you can see what this code basically does (here from start top left to end bottom right)
    * the red dots are the original start and end points
    * the blue lines are the perpendicular lines
    * the green dots are the final virtual fingers based on the finger-count setup in the action itself
    * the green lines are the final swipe lines for each finger

image

And here is a simulator screenshot vor a 3-finger-swipe from top right to bottom left:
image

### CODE REVIEW

**Comment by pixel-shock** [comment]
Sorry @sds100 to bother you with that, but did you had any time to have a look at this one?
If you like it and merge it, is there any chance to trigger a new build and relase (to play store etc.)?

Cheers & THANK YOU
Tino

**Comment by sds100** [comment]
Hi, it's still on my to-do list to review this 😄

**Comment by pixel-shock** [comment]
Alright ... I know ... as a Dev it's hard to do such things after work ... same for me ... it's always tricky to get time slot for private stuff

**Comment by sds100** [comment]
everything looks good so will create a new release

**Comment by pixel-shock** [comment]
Thank you Seth, made my day. Have a nice weekend 🍻🥳

**Pull request merged**
